$(document).ready(function(){
	$(".results").hide();
	$('.details').hide();
	$('.itemGO').click(function(){
		$(".results").show();
	})
	$('.results').click(function(){
		$(".details").show();
	})
});